// /** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                primary: "#4A82AE",
                "secondary-dark": "#0F2A44",
                "on-tertiary-fixed": "#2a1800",
                "tertiary-fixed": "#ffddb6",
                "on-secondary-fixed-variant": "#304864",
                secondary: "#48607d",
                "surface-tint": "#26638d",
                "inverse-on-surface": "#f0f0f4",
                "secondary-fixed-dim": "#b0c9ea",
                "surface-container-low": "#f3f3f7",
                "on-surface-variant": "#41474e",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#001d36",
                "primary-fixed": "#cce5ff",
                "on-tertiary": "#ffffff",
                "inverse-primary": "#95ccfc",
                "on-error": "#ffffff",
                "surface-container-high": "#e7e8ec",
                "on-tertiary-fixed-variant": "#643f00",
                "surface-variant": "#e1e2e6",
                "error-container": "#ffdad6",
                "surface-dim": "#d9dade",
                "secondary-container": "#c3dcfe",
                "on-primary-fixed": "#001e31",
                "on-primary-fixed-variant": "#004b73",
                "on-background": "#191c1f",
                "on-surface": "#191c1f",
                "outline-variant": "#c1c7cf",
                "on-secondary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed": "#d1e4ff",
                background: "#f8f9fd",
                "tertiary-fixed-dim": "#f8bb6c",
                "surface-container-highest": "#e1e2e6",
                "inverse-surface": "#2e3134",
                "primary-container": "#4179a5",
                "on-secondary-container": "#49617e",
                error: "#ba1a1a",
                surface: "#f8f9fd",
                tertiary: "#7f5309",
                "surface-bright": "#f8f9fd",
                "on-tertiary-container": "#fffbff",
                "on-primary": "#ffffff",
                "on-primary-container": "#fdfcff",
                "primary-fixed-dim": "#95ccfc",
                "surface-container": "#edeef2",
                outline: "#71787f",
                "tertiary-container": "#9b6b23",
            },
            fontFamily: {
                headline: ["Inter", "sans-serif"],
                body: ["Inter", "sans-serif"],
                label: ["Inter", "sans-serif"],
                inter: ['Inter', 'sans-serif'],
                manrope: ['Manrope', 'sans-serif'],
            }
        },
        borderRadius: {
            DEFAULT: "0.125rem",
            lg: "0.25rem",
            xl: "0.5rem",
            full: "0.75rem",
        },
    },
    plugins: [],
}

